# -*- coding: utf-8 -*-
"""Banco de dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DNOjcNErjoAIiUhKOdS2D2CUifHVmMhQ
"""

import sqlite3

conn = sqlite3.connect('meuBanco.db')
print("Conexão aberta! ")

conn.execute('''
  CREATE TABLE IF NOT EXISTS alunos (
    matricula integer,
    nome string,
    nota integer
  );
''')
conn.commit()
print("Tabela criada com sucesso!")

conn.execute("INSERT INTO alunos VALUES(1001, 'Hildegard', 8);")
conn.execute("INSERT INTO alunos VALUES(1002, 'Diego', 6);")
conn.execute("INSERT INTO alunos VALUES(1003, 'Maria', 3);")
conn.execute("INSERT INTO alunos VALUES(1004, 'Renan', 7);")
conn.execute("INSERT INTO alunos VALUES(1005, 'José', 5);")
conn.execute("INSERT INTO alunos VALUES(1006, 'Rafael', 10);")
conn.execute("INSERT INTO alunos VALUES(1007, 'Bruna', 10);")
conn.execute("INSERT INTO alunos VALUES(10088, 'Lorenzo', 9);")
conn.commit()
print("Dados Incluidos com sucesso!")

import pandas as pd

dadosAlunos = conn.execute('''
  SELECT matricula, nome, nota
  FROM alunos;

''')

for aluno in dadosAlunos:
  print("Matricula:", aluno[0])
  print("Nome:", aluno[1])
  print("Nota:", aluno[2],"\n")

conn.close()