# -*- coding: utf-8 -*-
"""CEPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G5giEetv1K9CWpDfwgTSV66D8QRMWQj6
"""

import requests as rq

novaPesquisa= True

while novaPesquisa:
  if novaPesquisa:
    def buscaCep():
      print("-----------------------------------")
      print("--------- CEPYTHON 0.0.1 ----------")
      print("-----------------------------------")
      cep = input('Digite  o CEP desejado:\nInserir apenas 08 dígitos e sem traços!!!\n')
      request = rq.get('https://viacep.com.br/ws/{}/json/'.format(cep))
      endereco = request.json()

      print("============>CEP Encontrado!===============")
      print('Cep: {}'.format(endereco['cep']))
      print(f"Cidade:  {endereco['localidade']}")
      print('Estado: ',endereco['uf'])
      print('Estado: ',endereco['logradouro'])
  buscaCep()

  novaPesquisa = input("Você desseja fazer nova pesquisa? \n1-Sim ou \n2-Não \n")
  if novaPesquisa == "nao" or novaPesquisa == "não":
    novaPesquisa =False
    print("Obrigado por usar a minha aplicação!")